name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 'main'

jobs:
  quality:
    strategy:
      matrix:
        node-version: [18.6.0] 
        os: [ubuntu-latest] 
        

    runs-on: ${{ matrix.os }}

   

    steps:
    - name: checkout the repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: cache
      uses: actions/cache@v4
      id: cache
      with:
       path: path/to/dependencies
       key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }} 
 
        
    - name: install dependences    
      run: npm ci

    - name: test  
      run: npm test
  
  publish:
    strategy:
      matrix:
        node-version: [18.6.0] 
        os: [ubuntu-latest] 

    runs-on: ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/main' }} 
    permissions:  
      contents: write
      issues: write
      pull-requests: write
      id-token: write
     
    needs: [quality]
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependences    
      run: npm ci
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
    - name: push    
      run: npm run semantic-release


      

        
