name: Node.js CI

on:
  push:
    branches: [ Feature ]
  pull_request:
    branches: 'main'

jobs:
  quality:
    strategy:
      matrix:
        node-version: [18.6.0] 
        os: [ubuntu-latest] 
        

    runs-on: ${{ matrix.os }}

   

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
  
  publish:
    strategy:
      matrix:
        node-version: [18.6.0] 
        os: [ubuntu-latest] 

    runs-on: ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run semantic-release
      env: 
        ## NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
